# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1051, 582)
        font = QtGui.QFont()
        font.setPointSize(14)
        LoginWindow.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setContentsMargins(-1, 40, 9, 30)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, 20, 0)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.labelLogin = QtWidgets.QLabel(LoginWindow)
        self.labelLogin.setObjectName("labelLogin")
        self.gridLayout.addWidget(self.labelLogin, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(LoginWindow)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.labelPassword = QtWidgets.QLabel(LoginWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(LoginWindow)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.labelOrganization = QtWidgets.QLabel(LoginWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelOrganization.setFont(font)
        self.labelOrganization.setObjectName("labelOrganization")
        self.gridLayout.addWidget(self.labelOrganization, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(LoginWindow)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.btnEnter = QtWidgets.QPushButton(LoginWindow)
        self.btnEnter.setObjectName("btnEnter")
        self.gridLayout_2.addWidget(self.btnEnter, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Регистрация в программе"))
        self.labelLogin.setText(_translate("LoginWindow", "Логин"))
        self.labelPassword.setText(_translate("LoginWindow", "Пароль"))
        self.labelOrganization.setText(_translate("LoginWindow", "Войти как"))
        self.comboBox.setItemText(0, _translate("LoginWindow", "Управляющая компания"))
        self.comboBox.setItemText(1, _translate("LoginWindow", "Дорожная компания "))
        self.comboBox.setItemText(2, _translate("LoginWindow", "Транспортная компания"))
        self.btnEnter.setText(_translate("LoginWindow", "Войти "))
